% if tx_info.use_simulink_display
samp_rate = 4e6;    
    scope = dsp.TimeScope('SampleRate',      samp_rate, ...
                          'Title',           'Baseband QPSK Time Signal', ...
                          'TimeSpan',        1/samp_rate*(length(tx_info.base_iq_signal)+5000), ...
                          'YLimits',         [-1 1], ...
                          'ShowLegend',      true, ...
                          'ShowGrid',        true, ...
                          'Position',        [0 600 400 400]);
    step(scope, tx_info.base_iq_signal);
    release(scope);

hsa = dsp.SpectrumAnalyzer('SampleRate',      samp_rate, ...
                           'SpectrumType',    'Power density', ...
                           'SpectralAverages', 10, ...
                           'YLimits',         [-150 0], ...
                           'Title',           'Baseband QPSK Signal Spectrum', ...
                           'YLabel',          'Power spectral density', ...
                           'Position',        [400 600 400 400]);

% Show power spectral density of captured burst
step(hsa,tx_info.base_iq_signal(129:end));
release(hsa);
% end